Add support for ssh/git-credentials setup to docker entrypoint

diff --git a/bin/git-gau-entry b/bin/git-gau-entry
--- a/bin/git-gau-entry
+++ b/bin/git-gau-entry
@@ -1,3 +1,52 @@
 #!/bin/sh
 
-exec /usr/bin/git gau-exec "$GAU_REPO" "$@"
+GIT=/usr/bin/git
+MKDIR=/bin/mkdir
+SSH_ADD=/usr/bin/ssh-add
+SSH_AGENT=/usr/bin/ssh-agent
+
+# Print usage message and exit.
+if [ -z "${GAU_REPO}" ] || [ "${#}" -lt 1 ] || [ "${1:-h}" = "-h" ] || [ "${1:---help}" = "--help" ]; then
+    ${ECHO} "${0}: command [args...]" >&2
+    ${ECHO} "Environment variable GAU_REPO is required" >&2
+    exit 1
+fi
+
+GAU_SSH_DIR="${GAU_SSH_PRIVKEY_FILE:=${HOME}/.ssh}"
+GAU_SSH_PRIVKEY_FILE="${GAU_SSH_PRIVKEY_FILE:=${GAU_SSH_DIR}/id_rsa}"
+GAU_GIT_CREDENTIALS_FILE="${GAU_GIT_CREDENTIALS_FILE:=${GAU_SSH_DIR}/.git-credentials}"
+GAU_SSH_KNOWNHOSTS_FILE="${GAU_SSH_KNOWNHOSTS_FILE:=${GAU_SSH_DIR}/known_hosts}"
+
+# Optionally write git credentials file.
+if [ -n "${GAU_GIT_CREDENTIALS}" ]; then
+    if [ ! -e "${GAU_GIT_CREDENTIALS_FILE}" ]; then
+        (umask 077 && ${ECHO} "${GAU_GIT_CREDENTIALS}" > "${GAU_GIT_CREDENTIALS_FILE}")
+    fi
+fi
+
+# Optionally write an SSH private key file.
+if [ -n "${GAU_SSH_PRIVKEY}" ]; then
+    ${MKDIR} -p "${GAU_SSH_DIR}"
+    if [ ! -e "${GAU_SSH_PRIVKEY_FILE}" ]; then
+        (umask 077 && ${ECHO} "${GAU_SSH_PRIVKEY}" > "${GAU_SSH_PRIVKEY_FILE}")
+    fi
+fi
+
+# Optionally setup the SSH agent.
+if [ -n "${GAU_SSH_SETUP_AGENT}" ]; then
+    ${MKDIR} -p "${GAU_SSH_DIR}"
+    eval "$(${SSH_AGENT})"
+    if [ -e "${GAU_SSH_PRIVKEY_FILE}" ]; then
+        ${SSH_ADD} "${GAU_SSH_PRIVKEY_FILE}"
+    fi
+fi
+
+# Optionally setup the SSH known hosts file.
+if [ -n "${GAU_SSH_KNOWNHOSTS}" ]; then
+    ${MKDIR} -p "${GAU_SSH_DIR}"
+    if [ ! -e "${GAU_SSH_KNOWNHOSTS_FILE}" ]; then
+        ${ECHO} "${GAU_SSH_KNOWNHOSTS}" > "${GAU_SSH_KNOWNHOSTS_FILE}"
+    fi
+fi
+
+exec ${GIT} gau-exec "$GAU_REPO" "$@"
